# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6b41b06b64b4459770d1ba116c00180bd785d77844b190a59b5a0f2d23c9cf1f648f8391fd26e188481578822a6382961893238e4a62a8cc92268b9c40a66aaa

test:
  secret_key_base: 82fa73434e2912f20cea16bc929f2c2f03f1745e2a618ce5445fcaea6d7bbde147a4845637afe18a30c430a2b7e975e96c9ce5c5b88dc321af223d0fca536f63

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
